#!/usr/bash


# handle bashrc selection
if [[ "$SHELL " = *bash* ]]; then
    export ENV_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )"/.. && pwd )"
    alias sb='source ~/.bashrc'
    alias eb='vi ~/.bashrc'
elif [[ -n "$ZSH_NAME" ]]; then
    export ENV_ROOT=$0:a:h/..
    alias sb='source ~/.zshrc'
    alias eb='vi ~/.zshrc'
fi
if hash realpath >& /dev/null; then
    export ENV_ROOT=$(realpath $ENV_ROOT)
fi

source $ENV_ROOT/shell/$1
alias ep="vi $ENV_ROOT/shell/$1"

# alias
alias vi='vim'
alias ll='ls -hl'
alias la='ls -a'
alias rm='rm -i'
alias gitk='gitk --all'
alias c='clear'
alias m='make'
alias mmi='make -j8 install'
alias mmr='make -j && ./run'
alias h='history'
alias cd1='cd ../'
alias cd2='cd ../../'
alias cd3='cd ../../../'
alias cd4='cd ../../../../'
alias cd5='cd ../../../../../'
alias fg1='fg %1'
alias fg2='fg %2'
alias fg3='fg %3'
alias fg4='fg %4'
alias grep='grep -I'
alias cdenv="cd ${ENV_ROOT}"


PATH=$PATH:$ENV_ROOT/script

function wcd
{
    if [ $# -ne 1 ]; then
        echo "only accpet 1 argument"
        return 1
    fi
    file=$(which $1)
    DIR=$(dirname $file)
    cd $DIR
}
function wvi
{
    if [ $# -ne 1 ]; then
        echo "only accpet 1 argument"
        return 1
    fi
    file=$(which $1)
    vi $file
}

PATH=$PATH:$ENV_ROOT/p4-wrapper/commands
