#!/usr/bash

HOST_NAME=$(hostname -s)

# handle bashrc selection
if [[ "$SHELL " = *bash* ]]; then
    export ENV_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )"/.. && pwd )"
    export ENV_ROOT=$(realpath $ENV_ROOT)
    if [[ "$HOST_NAME" = *Mac* ]]; then
        export IS_MAC=true
        source $ENV_ROOT/shell/bashrc.mac
        alias ep='vi $ENV_ROOT/shell/bashrc.mac'
    elif [[ "$HOST_NAME" = ubuntu-xenial ]]; then
        source $ENV_ROOT/shell/bashrc.cuda
        alias ep='vi $ENV_ROOT/shell/bashrc.cuda'
    else
        echo "unknow host $HOST_NAME"
    fi
elif [[ "$SHELL " = *zsh* ]]; then
    export ENV_ROOT=$0:a:h/..
    export ENV_ROOT=$(realpath $ENV_ROOT)
    alias sz='source ~/.zshrc'
    alias ez='vi ~/.zshrc'
    source $ENV_ROOT/shell/zshrc.mac
    alias ep='vi $ENV_ROOT/shell/zshrc.mac'
fi

#ep stand for edit persional rc


# alias
alias vi='vim'
alias ll='ls -hl'
alias la='ls -a'
alias rm='rm -i'
alias gitk='gitk --all'
alias c='clear'
alias m='make'
alias me='make 2>&1 | less'
alias mm='make -j8'
alias mmi='make -j8 install'
alias mmr='make -j && ./run'
alias h='history'
alias cd1='cd ../'
alias cd2='cd ../../'
alias cd3='cd ../../../'
alias cd4='cd ../../../../'
alias cd5='cd ../../../../../'
alias fg1='fg %1'
alias fg2='fg %2'
alias fg3='fg %3'
alias grep='grep -I'
alias cdenv="cd ${ENV_ROOT}"

alias eb='vi $ENV_ROOT/shell/mainrc'


PATH=$PATH:$ENV_ROOT/script

function wcd
{
    if [ $# -ne 1 ]; then
        echo "only accpet 1 argument"
        return 1
    fi
    file=$(which $1)
    DIR=$(dirname $file)
    cd $DIR
}
function wvi
{
    if [ $# -ne 1 ]; then
        echo "only accpet 1 argument"
        return 1
    fi
    file=$(which $1)
    vi $file
}
