FROM pytorch/glow/sophon/dev:0.1
RUN apt-get install -y ocl-icd-libopencl1
RUN apt-get install -y opencl-headers
RUN apt-get install -y clinfo
RUN apt-get install -y ocl-icd-opencl-dev
RUN apt-get install -y vim
RUN apt-get install -y gdb cgdb
ENV HOME=/tmp
