#!/bin/bash -e

git fetch -p --all
git checkout origin/master
tmpfile=$(mktemp /tmp/eric-temp.XXXXXX)
git branch --merged | grep -v HEAD > ${tmpfile}
vi ${tmpfile}
xargs git branch -d < ${tmpfile}
rm -fr ${tmpfile}


