#!/bin/bash
set -eu

# find target
if [ "$#" -eq 1 ]; then
    target=$1
elif git show-branch remotes/origin/main >& /dev/null; then
    target=main
else
    target=master
fi

# check before ref target
if git show-branch remotes/origin/$target >& /dev/null; then
    set -x
    git symbolic-ref m refs/remotes/origin/$target
else
    # show error message
    git show-branch remotes/origin/$target 
fi



