#!/bin/bash

remote_branch=${1-origin/master}
git fetch -p --all
tmpfile=$(mktemp /tmp/eric-temp.XXXXXX)
git branch --merged $remote_branch | grep -v HEAD > ${tmpfile}
if [ ! -s ${tmpfile} ]
then
    echo no merged branch
    exit
fi
vi ${tmpfile}
xargs git branch -D < ${tmpfile}
rm -fr ${tmpfile}


