#!/bin/bash
set -euxo pipefail

pushd /Volumes/Untitled/DCIM/100MEDIA
if ls *.MP4 &> /dev/null ; then
    my exif *.MP4
fi
if ls *.mp4 &> /dev/null ; then
    open ~/Dropbox/Camera\ Uploads
    rsync -avP *.mp4 ~/Dropbox/Camera\ Uploads
    rm -fr *.mp4
fi
popd
diskutil eject /Volumes/Untitled

