#!/usr/bin/env python3

import subprocess
import os
import argparse


def concatenate_videos(video_list, output_filename, copy, fast):

    temp_file_path = "input_videos_for_concat.txt"
    with open(temp_file_path, "w") as f:
        for video in video_list:
            if not os.path.exists(video):
                print(f"警告：找不到影片檔案 '{video}'，將跳過。")
                continue
            f.write(f"file '{video}'\n")

    cmd_a = []
    cmd = []
    if copy:
        cmd = ["-c", "copy"]
    else:
        cmd += ["-fps_mode", "cfr"]
        if fast:
            cmd += ["-c:v", "h264_videotoolbox"]
            cmd_a += ["-hwaccel", "videotoolbox"]
            cmd += ["-vf", "scale=160:-1"]
            cmd += ['-preset', 'ultrafast']
            cmd += ["-crf", "50"]
        else:
            cmd += ["-c:v", "libx265"]
            cmd += ['-tag:v', 'hvc1']
            cmd += ["-crf", "28"]
    ffmpeg_command = ["ffmpeg", *cmd_a, "-f", "concat", "-safe", "0", "-i", temp_file_path, *cmd, output_filename]

    print(' '.join(ffmpeg_command))

    try:
        subprocess.run(ffmpeg_command, check=True)
        print(f"影片已成功合併為 '{output_filename}'")
    except subprocess.CalledProcessError as e:
        print(f"執行 FFmpeg 時發生錯誤：{e}")
    except FileNotFoundError:
        print("錯誤：找不到 FFmpeg。請確保 FFmpeg 已安裝並在您的系統 PATH 中。")
    finally:
        if os.path.exists(temp_file_path):
            os.remove(temp_file_path)
            print(f"已刪除暫存檔案：{temp_file_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(formatter_class=argparse.RawTextHelpFormatter)

    parser.add_argument("-i",
                        "--input",
                        nargs="+",
                        required=True,
                        help=("要合併的輸入影片檔案路徑。\n"
                              "可以輸入多個檔案名，用空格分隔，例如：\n"
                              "  video1.mp4 video2.mp4 video3.mp4"))
    parser.add_argument('-c', '--copy', action="store_true", help='copy instead re-encode')
    parser.add_argument('-f', '--fast', action="store_true", help='fast encoding to check format')

    parser.add_argument(
        "-o",
        "--output",
        type=str,
        default="output.mp4",  # 預設輸出檔名
        help="合併後輸出影片檔案的名稱 (預設: merged_output.mp4)")

    args = parser.parse_args()

    # 呼叫合併函數
    concatenate_videos(args.input, args.output, args.copy, args.fast)
