#!/usr/bin/env python3

import argparse
from exif import exif

if __name__ == '__main__':
    # Get input file name
    parser = argparse.ArgumentParser("my exif")
    parser.add_argument('-i', '--input', nargs='+', help='input files')
    parser.add_argument("--hours", type=int, required=True, help="偏移小時數，正數為加，負數為減")
    args = parser.parse_args()
    for f in args.input:
        print(f)
        ta = exif.tag_agent(f)
        ta.shift_create_date(args.hours)
