#!/usr/bin/env python3

import argparse
import os
from datetime import datetime
import re
import subprocess

if __name__ == '__main__':

    parser = argparse.ArgumentParser()
    parser.add_argument("-i", '--input', nargs='+', help='input files')
    parser.add_argument("-n", '--dry', action='store_true', help='dry run')
    args = parser.parse_args()

    re_n = re.compile(r'(.*)(\d{14})(.*)')
    print(f"handling {len(args.input)} files")
    for fname in args.input:
        r = re_n.match(fname)
        if r:
            name, datetime_str, ext = r.groups()
            datetime_str = datetime.strptime(datetime_str, '%Y%m%d%H%M%S').strftime('%Y-%m-%d %H.%M.%S')
            cmd = ['mv', fname, f'{datetime_str}{ext}']
            print(' '.join(cmd))
            if not args.dry:
                subprocess.run(cmd)
