#!/usr/bin/env python3
import os
import re
import argparse

parser = argparse.ArgumentParser("my photo")
parser.add_argument('-n', '--dry', action="store_true", help='dry run')
parser.add_argument('-y', '--year', action="store_true", help='dry run')
args = parser.parse_args()

for f in os.listdir():
    if os.path.isfile(f):
        m = re.match(r'(\d{4}-\d{2}-\d{2}) \d{2}.\d{2}.\d{2}.*', f)
        if m:
            dirname = m.group(1)
            if args.year:
                dirname = os.path.join(dirname[:4], dirname)
            os.makedirs(dirname, exist_ok=True)
            if not args.dry:
                os.rename(f, os.path.join(dirname, f))
            print(f'move {f} to {dirname}')
    elif os.path.isdir(f) and args.year:
        m = re.match(r'(\d{4})-\d{2}-\d{2}', f)
        if m:
            dirname = m.group(1)
            os.makedirs(dirname, exist_ok=True)
            if not args.dry:
                os.rename(f, os.path.join(dirname, f))
            print(f'move {f} to {dirname}')
