#!/usr/bin/env python3
import os
import re
import argparse

parser = argparse.ArgumentParser("my photo")
parser.add_argument('-n', '--dry', action="store_true", help='dry run')
args = parser.parse_args()

for f in os.listdir():
    if not os.path.isfile(f):
        continue
    m = re.match(r'(\d{4}-\d{2}-\d{2}) \d{2}.\d{2}.\d{2}.*', f)
    if m:
        dirname = m.group(1)
        if not os.path.exists(dirname):
            os.makedirs(dirname)
        if not args.dry:
            os.rename(f, os.path.join(dirname, f))
        print(f'move {f} to {dirname}')
