#!/usr/bash

# handle bashrc selection
rc_sel_path=
if [ ! -f ~/.bashrc.sel ]; then
    echo "~/.bashrc.sel not found! Creating one..."
    cp ${ENV_ROOT}/shell/sel/bashrc.sel ~/.bashrc.sel
fi
source  ~/.bashrc.sel

# alias
alias vi='vim'
alias ll='ls -hl'
alias la='ls -a'
alias rm='rm -i'
alias gitk='gitk --all'
alias c='clear'
alias m='make'
alias me='make 2>&1 | less'
alias mm='make -j8'
alias mmi='make -j8 install'
alias mmr='make -j && ./run'
alias h='history'
alias cd1='cd ../'
alias cd2='cd ../../'
alias cd3='cd ../../../'
alias cd4='cd ../../../../'
alias cd5='cd ../../../../../'
alias fg1='fg %1'
alias fg2='fg %2'
alias fg3='fg %3'
alias grep='grep -I'
alias cdenv="cd ${ENV_ROOT}"

alias eb='vi $ENV_ROOT/shell/common/bashrc'


PATH=$PATH:$ENV_ROOT/script

function wcd
{
    file=$(which $1)
    DIR=$(dirname $file)
    cd $DIR
}
function wvi
{
    file=$(which $1)
    vi $file
}
