#!/usr/bash

alias vi='vim'
alias ll='ls -hla'
alias la='ls -a'
alias rm='rm -i'
alias gitk='gitk --all'
alias c='clear'
alias m='make'
alias me='make 2>&1 | less'
alias mm='make -j8'
alias mmi='make -j8 install'
alias mmr='make -j && ./run'
alias h='history'
alias cd1='cd ../'
alias cd2='cd ../../'
alias cd3='cd ../../../'
alias cd4='cd ../../../../'
alias cd5='cd ../../../../../'
alias fg1='fg %1'
alias fg2='fg %2'
alias fg3='fg %3'
alias grep='grep -I'
alias cdenv="cd ${ENV_ROOT}"


PATH=$PATH:$ENV_ROOT/script

rc_sel_path=${HOME}/.bashrc.sel
if [ ! -f ${rc_sel_path} ]; then
    echo "${rc_sel_path} not found! Creating one..."
    cp ${ENV_ROOT}/shell/sel/bashrc.sel ${rc_sel_path}
fi
source ${rc_sel_path}
alias ep="vi ${ENV_ROOT}/shell/sel/${RC_SEL}"
